/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PpnbmRouteImport } from './routes/ppnbm'
import { Route as PpnRouteImport } from './routes/ppn'
import { Route as Pph42RouteImport } from './routes/pph4-2'
import { Route as Pph23RouteImport } from './routes/pph23'
import { Route as Pph22RouteImport } from './routes/pph22'
import { Route as Pph21RouteImport } from './routes/pph21'
import { Route as IndexRouteImport } from './routes/index'

const PpnbmRoute = PpnbmRouteImport.update({
  id: '/ppnbm',
  path: '/ppnbm',
  getParentRoute: () => rootRouteImport,
} as any)
const PpnRoute = PpnRouteImport.update({
  id: '/ppn',
  path: '/ppn',
  getParentRoute: () => rootRouteImport,
} as any)
const Pph42Route = Pph42RouteImport.update({
  id: '/pph4-2',
  path: '/pph4-2',
  getParentRoute: () => rootRouteImport,
} as any)
const Pph23Route = Pph23RouteImport.update({
  id: '/pph23',
  path: '/pph23',
  getParentRoute: () => rootRouteImport,
} as any)
const Pph22Route = Pph22RouteImport.update({
  id: '/pph22',
  path: '/pph22',
  getParentRoute: () => rootRouteImport,
} as any)
const Pph21Route = Pph21RouteImport.update({
  id: '/pph21',
  path: '/pph21',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pph21': typeof Pph21Route
  '/pph22': typeof Pph22Route
  '/pph23': typeof Pph23Route
  '/pph4-2': typeof Pph42Route
  '/ppn': typeof PpnRoute
  '/ppnbm': typeof PpnbmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pph21': typeof Pph21Route
  '/pph22': typeof Pph22Route
  '/pph23': typeof Pph23Route
  '/pph4-2': typeof Pph42Route
  '/ppn': typeof PpnRoute
  '/ppnbm': typeof PpnbmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pph21': typeof Pph21Route
  '/pph22': typeof Pph22Route
  '/pph23': typeof Pph23Route
  '/pph4-2': typeof Pph42Route
  '/ppn': typeof PpnRoute
  '/ppnbm': typeof PpnbmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pph21'
    | '/pph22'
    | '/pph23'
    | '/pph4-2'
    | '/ppn'
    | '/ppnbm'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pph21' | '/pph22' | '/pph23' | '/pph4-2' | '/ppn' | '/ppnbm'
  id:
    | '__root__'
    | '/'
    | '/pph21'
    | '/pph22'
    | '/pph23'
    | '/pph4-2'
    | '/ppn'
    | '/ppnbm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Pph21Route: typeof Pph21Route
  Pph22Route: typeof Pph22Route
  Pph23Route: typeof Pph23Route
  Pph42Route: typeof Pph42Route
  PpnRoute: typeof PpnRoute
  PpnbmRoute: typeof PpnbmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ppnbm': {
      id: '/ppnbm'
      path: '/ppnbm'
      fullPath: '/ppnbm'
      preLoaderRoute: typeof PpnbmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ppn': {
      id: '/ppn'
      path: '/ppn'
      fullPath: '/ppn'
      preLoaderRoute: typeof PpnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pph4-2': {
      id: '/pph4-2'
      path: '/pph4-2'
      fullPath: '/pph4-2'
      preLoaderRoute: typeof Pph42RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pph23': {
      id: '/pph23'
      path: '/pph23'
      fullPath: '/pph23'
      preLoaderRoute: typeof Pph23RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pph22': {
      id: '/pph22'
      path: '/pph22'
      fullPath: '/pph22'
      preLoaderRoute: typeof Pph22RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pph21': {
      id: '/pph21'
      path: '/pph21'
      fullPath: '/pph21'
      preLoaderRoute: typeof Pph21RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Pph21Route: Pph21Route,
  Pph22Route: Pph22Route,
  Pph23Route: Pph23Route,
  Pph42Route: Pph42Route,
  PpnRoute: PpnRoute,
  PpnbmRoute: PpnbmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
